version: '3.7'

services: 
  carbone:
    image: node:carbone-app-v0.0.1
    ports:
        - 3000:3000
    environment:
      - TZ=${TZ:-Asia/Bangkok}
      - SERVICE_ID=carbone-app
  go-api:
    image: go-api:v0.0.1
    environment:
      - TZ=${TZ:-Asia/Bangkok}
      - SERVICE_ID=carbone-app

networks: 
  default: 
    external: 
      name: local